### ISSUE TITLE
Can’t moving focus from an image to an adjacent image using up/down arrow.

### ISSUE THREAD

**Issue by houkanshan** [bkniffler/draft-wysiwyg#10]
Here is a gif for it, the key press sequence is: down, down, up, up.

![gif](https://cloud.githubusercontent.com/assets/657962/15897397/e21e2e18-2dc6-11e6-972d-78c680ed6f6f.gif)

---

I think part of the reason is [draft-js-focus-plugin:L43..L45](https://github.com/draft-js-plugins/draft-js-plugins/blob/3566803c3a5b74971f6e2baa982c2b2c9483eb15/draft-js-focus-plugin/src/index.js#L43..L45), in which the `activeBlock` is `undefined` and the condition in `if` will always be `false`.

~~But I suspect by setting the `selectionState` focus to the `block-focus` still won't make it focused, because the `block-focus` doesn't handle the update of the `selectionState`. Meanwhile I think neither handling the update of `selectionState` nor setting focus directly from another `block-focus` would be an easy solution here, what's your idea?~~

Thanks, and also thanks for your project!

**Comment by bkniffler** [comment]
Hi @houkanshan,
Thanks for reporting, I've just pushed a commit and I'll publish and update everything today. The focus stuff is totally complicated, hope iI'll find an easier solution sometime.

**Comment by houkanshan** [comment]
> The focus stuff is totally complicated

+1

Looking forward to it, thanks!
