### ISSUE TITLE
Unable to initialize contents from storage

### ISSUE THREAD

**Issue by cameracker** [bkniffler/draft-wysiwyg#22]
This is a cool editor if the heroku app example is to be believed.

However, it doesn't work. I can't get it to render document contents from my store. I've tried replicating what you have in your example, and I've tried using other people's examples. After a couple of days, I think what I really need is for someone to update the documentation and clearly indicate

1. What sort of type needs to go into the value props. Neither the example, nor the source is using PropType validation so all I have are best guesses, which is clearly not good enough.
2. How to get from whatever you're storing in your DB, in very clear terms, to what the Wysiwyg editor component expects.

I cannot adequately express how disheartening it is to run across an impressive library like this only to run into an inability to use it because of documentation problems. 

Please address this or give me some help.

Thanks very much for your time.

**Comment by wkw** [comment]
BK's stuff is cool. Last year we evaluated a few draft-js editors which seemed like good starting points. Ended up going with this one and successfully built a great custom editor inside WordPress with it. https://github.com/globocom/megadraft have a look if you haven't seen it yet.

**Comment by cameracker** [comment]
Yeah, using the above editor instead. Thanks!
