### ISSUE TITLE
Example source code.

### ISSUE THREAD

**Issue by vcanales** [bkniffler/draft-wysiwyg#7]
Hi, I used your editor back when version was 0.0.26. Now, using the same code I used back then does not work. Would it be possible for you to post the example source code (if it's up to date with the current version of the editor) to check out what exactly changed?

**Comment by bkniffler** [comment]
Sorry for the inconvinience, the only major change in the API is the renaming of `updateValue` to `onChange` to provide a more consistent experience with other edits. An example can be found here https://github.com/bkniffler/draft-wysiwyg/blob/master/example/container.js

If you got any more questions, feel free to ask!
